# Generated by Django 3.2.8 on 2022-07-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_first_name_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
